name: CodeWarriors-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup pem file
        run: |
          echo "${{ secrets.MufrinDev_key17 }}" > DevOps-key.pem
          chmod 400 DevOps-key.pem

      - name: copy app.py to EC2
        run: scp -o StrictHostKeyChecking=no -i DevOps-key.pem app.py ec2-user@52.66.201.115:/home/ec2-user/

      - name: copy requirements.txt to EC2
        run: scp -o StrictHostKeyChecking=no -i DevOps-key.pem requirements.txt ec2-user@52.66.201.115:/home/ec2-user/

      - name: deploy and run app
        run: |
          ssh -o StrictHostKeyChecking=no -i DevOps-key.pem ec2-user@52.66.201.115<< 'EOF'
          cd /home/ec2-user

          # stop old app if running
          pkill -f app.py || true

          # setup virtual environment
          python3 -m venv venv
          source venv/bin/activate

          pip3 install -r requirements.txt

          # run app in background (IMPORTANT)
          nohup python3 app.py > app.log 2>&1 &

          echo "Application deployed on port 5001"
          EOF
